config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  resources :bill_payments
  resources :members
  resources :groups
  resources :users do
    member do
     get 'update_pending'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bill_payment.rb
class BillPayment < ApplicationRecord
  belongs_to :group
  after_create :calculate_split

  def calculate_split
    amount = self.bill_amount
    members_count = self.group.users.count
    members = self.group.users
    split_amount = (amount/members_count).to_d
    members.each do |member|
      member.money_to_be_paid = split_amount
      member.pending = true
      member.save!
    end
  end
end

app/controllers/bill_payments_controller.rb
class BillPaymentsController < ApplicationController
  before_action :set_bill_payment, only: [:show, :edit, :update, :destroy]

  # GET /bill_payments
  # GET /bill_payments.json
  def index
    @bill_payments = BillPayment.all
  end

  # GET /bill_payments/1
  # GET /bill_payments/1.json
  def show
  end

  # GET /bill_payments/new
  def new
    @bill_payment = BillPayment.new
  end

  # GET /bill_payments/1/edit
  def edit
  end

  # POST /bill_payments
  # POST /bill_payments.json
  def create
    @bill_payment = BillPayment.new(bill_payment_params)

    respond_to do |format|
      if @bill_payment.save
        format.html { redirect_to @bill_payment, notice: 'Bill payment was successfully created.' }
        format.json { render :show, status: :created, location: @bill_payment }
      else
        format.html { render :new }
        format.json { render json: @bill_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bill_payments/1
  # PATCH/PUT /bill_payments/1.json
  def update
    respond_to do |format|
      if @bill_payment.update(bill_payment_params)
        format.html { redirect_to @bill_payment, notice: 'Bill payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill_payment }
      else
        format.html { render :edit }
        format.json { render json: @bill_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_payments/1
  # DELETE /bill_payments/1.json
  def destroy
    @bill_payment.destroy
    respond_to do |format|
      format.html { redirect_to bill_payments_url, notice: 'Bill payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill_payment
      @bill_payment = BillPayment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bill_payment_params
      params.require(:bill_payment).permit(:bill_amount, :group_id, :bill_purpose, :paid_by )
    end
end

app/helpers/bill_payments_helper.rb
module BillPaymentsHelper
end

app/views/bill_payments/_form.html.erb
<%= simple_form_for(@bill_payment) do |f| %>


  
    <%= f.input :bill_amount %>
    <%= f.input :bill_purpose %>
    <%= f.input :paid_by, collection: User.all, value_method: :name,label: "Paid by" %>
    <%= f.association :group %>
    <%= f.button :submit, class: "btn-primary"  %>
    
<% end %>

app/views/bill_payments/edit.html.erb
<h1>Editing Bill Payment</h1>

<%= render 'form', bill_payment: @bill_payment %>

<%= link_to 'Show', @bill_payment %> |
<%= link_to 'Back', bill_payments_path %>

app/views/bill_payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bill Payments</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Bill amount</th>
      <th>Group</th>
      <th>Bill Purpose</th>
      <th>Paid by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bill_payments.each do |bill_payment| %>
      <tr>
        <td><%= bill_payment.bill_amount %></td>
        <td><%= bill_payment.group.name %></td>
        <td><%= bill_payment.bill_purpose %></td>
        <td><%= bill_payment.paid_by %></td>
        <td><%= link_to 'Show', bill_payment %></td>
        <td><%= link_to 'Edit', edit_bill_payment_path(bill_payment) %></td>
        <td><%= link_to 'Destroy', bill_payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill Payment', new_bill_payment_path %>

app/views/bill_payments/new.html.erb
<h1>New Bill Payment</h1>

<%= render 'form', bill_payment: @bill_payment %>

<%= link_to 'Back', bill_payments_path %>

app/views/bill_payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bill amount:</strong>
  <%= @bill_payment.bill_amount %>
</p>

<p>
  <strong>Bill purpose:</strong>
  <%= @bill_payment.bill_purpose %>
</p>

<p>
  <strong>Paid by:</strong>
  <%= @bill_payment.paid_by %>
</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Money to be paid</th>
      <th>Pending</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bill_payment.group.users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.money_to_be_paid %></td>
        <td><%= user.pending %></td>
        <td><%= link_to 'Settle',update_pending_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_bill_payment_path(@bill_payment) %> |
<%= link_to 'Back', bill_payments_path %>